DROP PROCEDURE IF EXISTS SP_CRUD_ALUMNOS_CERTIFICADOS;
CREATE PROCEDURE SP_CRUD_ALUMNOS_CERTIFICADOS(
  IN $METODO VARCHAR(30),
  IN $NRO_DOC VARCHAR(12),
  IN $LIBRO VARCHAR(10),
  IN $FOLIO VARCHAR(10),
  IN $NUMERO VARCHAR(10),
  IN $XMLDOC LONGTEXT
)
BEGIN
  DECLARE i INT;
  DECLARE count INT;
  DECLARE exit HANDLER FOR SQLEXCEPTION
  BEGIN
      GET DIAGNOSTICS CONDITION 1
      @p1 = RETURNED_SQLSTATE, @p2 = MESSAGE_TEXT;
      SELECT @p2 AS MSG, 0 AS RESULTADO;
  END;

  DROP TEMPORARY TABLE IF EXISTS TEMP_ALUMNO;
  DROP TEMPORARY TABLE IF EXISTS TEMP_CERTIFICADO;

  CREATE TEMPORARY TABLE TEMP_ALUMNO (
    CODALUMNO CHAR(12),
    TP_DOC VARCHAR(10),
    NRO_DOC VARCHAR(12),
    NOMBRES VARCHAR(200),
    APELLIDOS VARCHAR(200),
    FECHA_NAC DATE,
    CORREO VARCHAR(100),
    NRO_CELULAR VARCHAR(20),
    ACTIVO TINYINT(1)
  );

  CREATE TEMPORARY TABLE TEMP_CERTIFICADO (
    IDCERTIFICADO INT,
    LIBRO VARCHAR(10),
    FOLIO VARCHAR(10),
    NUMERO VARCHAR(10),
    CODALUMNO CHAR(12),
    CURSO VARCHAR(500),
    NOMBRE VARCHAR(500),
    BASE64 TEXT,
    NOTA DECIMAL(4,2),
    ACTIVO TINYINT(1),
    FECHA_CERT DATE,
    FECHA_CREACION DATE,
    IDUSUARIO VARCHAR(20)
  );

  -- CREAR ALUMNO
  IF ($METODO = 'CREAR_ALUMNO') THEN
    IF EXISTS (SELECT 1 FROM ALUMNOS WHERE NRO_DOC = $NRO_DOC) THEN
      SELECT 'El alumno ya existe' AS MSG, 1 AS RESULTADO, CODALUMNO FROM ALUMNOS WHERE NRO_DOC = $NRO_DOC;
    ELSE
      INSERT INTO ALUMNOS (CODALUMNO, TP_DOC, NRO_DOC, NOMBRES, APELLIDOS, FECHA_NAC, CORREO, NRO_CELULAR, ACTIVO)
      SELECT 
        RIGHT(CONCAT('0000',ExtractValue($XMLDOC, '//ALUMNO/CODALUMNO')), 12),
        ExtractValue($XMLDOC, '//ALUMNO/TP_DOC'),
        ExtractValue($XMLDOC, '//ALUMNO/NRO_DOC'),
        ExtractValue($XMLDOC, '//ALUMNO/NOMBRES'),
        ExtractValue($XMLDOC, '//ALUMNO/APELLIDOS'),
        ExtractValue($XMLDOC, '//ALUMNO/FECHA_NAC'),
        ExtractValue($XMLDOC, '//ALUMNO/CORREO'),
        ExtractValue($XMLDOC, '//ALUMNO/NRO_CELULAR'),
        ExtractValue($XMLDOC, '//ALUMNO/ACTIVO');
      SELECT 'Alumno creado exitosamente' AS MSG, 1 AS RESULTADO, RIGHT(CONCAT('0000',ExtractValue($XMLDOC, '//ALUMNO/CODALUMNO')), 12) CODALUMNO;
    END IF;

  -- CARGAR CERTIFICADO
  ELSEIF ($METODO = 'CARGAR_CERTIFICADO') THEN
  
    /*
      CALL SP_CRUD_ALUMNOS_CERTIFICADOS('CARGAR_CERTIFICADO', '', '', '', '', 
      '<CERTIFICADO>
      <LIBRO>TEST</LIBRO>
      <FOLIO>2024</FOLIO>
      <NUMERO>00001</NUMERO>
      <CODALUMNO>000070048987</CODALUMNO>
      <CURSO>TEST</CURSO>
      <NOMBRE/>
      <BASE64></BASE64>
      <NOTA>18</NOTA>
      <ACTIVO>1</ACTIVO>
      <FECHA_CERT>2024-09-15</FECHA_CERT>
      <IDUSUARIO>FURIBE</IDUSUARIO>
      </CERTIFICADO>');
    */
    INSERT INTO CERTIFICADOS (LIBRO, FOLIO, NUMERO, CODALUMNO, CURSO, NOMBRE, BASE64, NOTA, ACTIVO, FECHA_CERT, FECHA_CREACION, IDUSUARIO)
    SELECT 
      ExtractValue($XMLDOC, '//CERTIFICADO/LIBRO'),
      ExtractValue($XMLDOC, '//CERTIFICADO/FOLIO'),
      ExtractValue($XMLDOC, '//CERTIFICADO/NUMERO'),
      ExtractValue($XMLDOC, '//CERTIFICADO/CODALUMNO'),
      ExtractValue($XMLDOC, '//CERTIFICADO/CURSO'),
      ExtractValue($XMLDOC, '//CERTIFICADO/NOMBRE'),
      ExtractValue($XMLDOC, '//CERTIFICADO/BASE64'),
      ExtractValue($XMLDOC, '//CERTIFICADO/NOTA'),
      ExtractValue($XMLDOC, '//CERTIFICADO/ACTIVO'),
      ExtractValue($XMLDOC, '//CERTIFICADO/FECHA_CERT'),
      CURRENT_DATE(),
      ExtractValue($XMLDOC, '//CERTIFICADO/IDUSUARIO');
    SELECT 'Certificado cargado exitosamente' AS MSG, 1 AS RESULTADO;
    
  -- ESTADO CERTIFICADO
  ELSEIF ($METODO = 'ESTADO_CERTIFICADO') THEN
    /*
      CALL SP_CRUD_ALUMNOS_CERTIFICADOS('ESTADO_CERTIFICADO', '', '', '', '', 1);
    */
    UPDATE CERTIFICADOS SET ACTIVO = CASE WHEN ACTIVO = 1 THEN 0 ELSE 1 END WHERE `IDCERTIFICADO` = $XMLDOC;
    SELECT 'Certificado actualizado exitosamente' AS MSG, 1 AS RESULTADO;
  
  -- LISTAR CERTIFICADOS
  ELSEIF ($METODO = 'LISTAR_CERTIFICADOS') THEN
    /*
      CALL SP_CRUD_ALUMNOS_CERTIFICADOS('LISTAR_CERTIFICADOS', '20240601', '', '', '', '20240920');
    */
    SELECT 
      C.IDCERTIFICADO, C.LIBRO, C.FOLIO, C.NUMERO, C.CODALUMNO, CONCAT(A.NOMBRES , ' ' , A.APELLIDOS) AS ALUMNO, A.NOMBRES, A.APELLIDOS, A.NRO_DOC, C.CURSO, C.NOMBRE, C.BASE64, C.NOTA, 
      DATE_FORMAT(C.FECHA_CERT, '%d/%m/%Y') AS FECHA_CERTIFICADO, C.ACTIVO, DATE_FORMAT(C.FECHA_CREACION, '%d/%m/%Y') AS FECHA_CREACION, C.IDUSUARIO, A.CORREO, A.FECHA_NAC, A.NRO_CELULAR 
    FROM CERTIFICADOS C
    JOIN ALUMNOS A ON C.CODALUMNO = A.CODALUMNO
    WHERE DATE_FORMAT(C.FECHA_CERT, '%Y%m%d') BETWEEN $NRO_DOC AND $XMLDOC;
    /*WHERE C.ACTIVO = 1;*/

  -- BUSCAR CERTIFICADO POR NRO_DOC
  ELSEIF ($METODO = 'BUSCAR_POR_NRO_DOC') THEN
    /*
      CALL SP_CRUD_ALUMNOS_CERTIFICADOS('BUSCAR_POR_NRO_DOC', '70048987', '', '', '', '');
    */
    SELECT 
      C.IDCERTIFICADO, C.LIBRO, C.FOLIO, C.NUMERO, C.CODALUMNO, A.NOMBRES, A.APELLIDOS, A.NRO_DOC, C.CURSO, C.NOMBRE, C.BASE64, C.NOTA, 
      DATE_FORMAT(C.FECHA_CERT, '%d/%m/%Y') AS FECHA_CERTIFICADO, C.ACTIVO 
    FROM CERTIFICADOS C
    JOIN ALUMNOS A ON C.CODALUMNO = A.CODALUMNO
    WHERE A.NRO_DOC = $NRO_DOC AND C.ACTIVO = 1;

  -- BUSCAR CERTIFICADO POR LIBRO, FOLIO Y NUMERO
  ELSEIF ($METODO = 'BUSCAR_POR_LIBRO_FOLIO_NUMERO') THEN
    /*
      CALL SP_CRUD_ALUMNOS_CERTIFICADOS('BUSCAR_POR_LIBRO_FOLIO_NUMERO', '', 'PYTHO', '2024', '00001', '');
    */
    SELECT 
      C.IDCERTIFICADO, C.LIBRO, C.FOLIO, C.NUMERO, C.CODALUMNO, A.NOMBRES, A.APELLIDOS, A.NRO_DOC, C.CURSO, C.NOMBRE, C.BASE64, C.NOTA, 
      DATE_FORMAT(C.FECHA_CERT, '%d/%m/%Y') AS FECHA_CERTIFICADO, C.ACTIVO 
    FROM CERTIFICADOS C
    JOIN ALUMNOS A ON C.CODALUMNO = A.CODALUMNO
    WHERE C.LIBRO = $LIBRO AND C.FOLIO = $FOLIO AND C.NUMERO = $NUMERO AND C.ACTIVO = 1;

  ELSE
    SELECT 'Método no válido' AS MSG, 0 AS RESULTADO;
  END IF;
END;